mysql:
  image: mysql
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=docker_db
    - MYSQL_USER=db_user
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  environment:
    - PMA_ARBITRARY=1
  restart: always
  ports:
   - "8080:80"
redis:
  image: redis
  container_name: php_redis
  ports:
   - "6379:6379"
php:
  image: mi7ter/php7
  container_name: php7
  links:
   - mysql:mysql
   - redis:redis
  ports:
   - "9000:9000"
  volumes:
<<<<<<< HEAD
   - ./html:/var/www/html/
=======
   - /c/Users/M7R_2/Documents/docker/html:/var/www/html/
>>>>>>> 83191736b8a5a048bf7ce335165521029584a796
nginx:
  image: nginx
  container_name: nginx_php7
  links:
   - php:fpm
   - mysql:mysql
  ports:
   - 80:80
  volumes:
<<<<<<< HEAD
   - ./html:/var/www/html/
   - ./nginx:/etc/nginx/conf.d/
=======
   - /c/Users/M7R_2/Documents/docker/html:/var/www/html/
   - /c/Users/M7R_2/Documents/docker/nginx:/etc/nginx/conf.d/
>>>>>>> 83191736b8a5a048bf7ce335165521029584a796
